Repository biodasturchi/docs, pull requests merged in 2023-04, with the labels that each got.

#36 Dev
  docs/.vitepress/config.ts
  docs/posts/2020-11-30-it-will-change-everything.md
  docs/posts/2022-01-05-how-to-build-modern-docs-with-vitepress.md
  docs/posts/2022-03-07-creating-markdown-blog-with-nextjs.md
  docs/posts/2022-04-13-ai-protein-folding-revolution.md
  docs/posts/2022-06-03-docking-on-ca-complex.md
  docs/posts/2022-09-29-ligand-docking-and-binding-site-analysis.md
  docs/posts/2022-11-01-alphafold-s-new-rival.md
  docs/posts/2023-04-20-mitoxondriya-nafas-olish.md
Labels: documentation

#38 fixed
  docs/.vitepress/config.ts
  docs/posts/2023-04-20-mitoxondriya-nafas-olish.md
  docs/posts/2023-04-23-gmx-introduction.md
Labels: bug

#40 changed
  README.md
  docs/.vitepress/cache/deps/@fortawesome_fontawesome-svg-core.js
  docs/.vitepress/cache/deps/@fortawesome_fontawesome-svg-core.js.map
  docs/.vitepress/cache/deps/@fortawesome_free-brands-svg-icons.js
  docs/.vitepress/cache/deps/@fortawesome_free-brands-svg-icons.js.map
  docs/.vitepress/cache/deps/@fortawesome_free-solid-svg-icons.js
  docs/.vitepress/cache/deps/@fortawesome_free-solid-svg-icons.js.map
  docs/.vitepress/cache/deps/@fortawesome_vue-fontawesome.js
  docs/.vitepress/cache/deps/@fortawesome_vue-fontawesome.js.map
  docs/.vitepress/cache/deps/_metadata.json
  docs/.vitepress/cache/deps/chunk-HHAQUBXP.js
  docs/.vitepress/cache/deps/chunk-HHAQUBXP.js.map
  docs/.vitepress/cache/deps/chunk-R647EDCJ.js
  docs/.vitepress/cache/deps/chunk-R647EDCJ.js.map
  docs/.vitepress/cache/deps/package.json
  docs/.vitepress/cache/deps/vue.js
  docs/.vitepress/cache/deps/vue.js.map
  docs/.vitepress/config.ts
  docs/.vitepress/config2/en.ts
  docs/.vitepress/config2/index.ts
  docs/.vitepress/config2/navbar/en.ts
  docs/.vitepress/config2/navbar/index.ts
  docs/.vitepress/config2/navbar/uz.ts
  docs/.vitepress/config2/share.ts
  docs/.vitepress/config2/sidebar/en.ts
  docs/.vitepress/config2/sidebar/index.ts
  docs/.vitepress/config2/sidebar/uz.ts
  docs/.vitepress/config2/uz.ts
  docs/.vitepress/config2/uz/index.md
  docs/.vitepress/config2/uz/pages/about.md
  docs/.vitepress/config2/uz/pages/blog.md
  docs/.vitepress/config2/uz/pages/contact.md
  docs/.vitepress/config2/uz/pages/sort/archive.md
  docs/.vitepress/config2/uz/pages/sort/category.md
  docs/.vitepress/config2/uz/pages/sort/tags.md
  docs/.vitepress/config2/uz/posts/2020-11-30-it-will-change-everything.md
  docs/.vitepress/config2/uz/posts/2022-01-05-how-to-build-modern-docs-with-vitepress.md
  docs/.vitepress/config2/uz/posts/2022-03-07-creating-markdown-blog-with-nextjs.md
  docs/.vitepress/config2/uz/posts/2022-04-13-ai-protein-folding-revolution.md
  docs/.vitepress/config2/uz/posts/2022-06-03-docking-on-ca-complex.md
  docs/.vitepress/config2/uz/posts/2022-09-29-ligand-docking-and-binding-site-analysis.md
  docs/.vitepress/config2/uz/posts/2022-11-01-alphafold-s-new-rival.md
  docs/.vitepress/config2/uz/posts/2023-04-20-mitoxondriya-nafas-olish.md
  docs/.vitepress/config2/uz/posts/2023-04-23-gmx-introduction.md
  docs/.vitepress/meta.ts
  docs/.vitepress/theme/components/Test.vue
  docs/.vitepress/theme/styles/blog.css
  docs/blog.md
  docs/index.md
  docs/pages/archive.md
  docs/pages/category.md
  docs/pages/contact.md
  docs/pages/tags.md
Labels: documentation

#41 initial commit
  .gitignore
  docs/.vitepress/cache/deps/@fortawesome_fontawesome-svg-core.js
  docs/.vitepress/cache/deps/@fortawesome_fontawesome-svg-core.js.map
  docs/.vitepress/cache/deps/@fortawesome_free-brands-svg-icons.js
  docs/.vitepress/cache/deps/@fortawesome_free-brands-svg-icons.js.map
  docs/.vitepress/cache/deps/@fortawesome_free-solid-svg-icons.js
  docs/.vitepress/cache/deps/@fortawesome_free-solid-svg-icons.js.map
  docs/.vitepress/cache/deps/@fortawesome_vue-fontawesome.js
  docs/.vitepress/cache/deps/@fortawesome_vue-fontawesome.js.map
  docs/.vitepress/cache/deps/_metadata.json
  docs/.vitepress/cache/deps/chunk-HHAQUBXP.js
  docs/.vitepress/cache/deps/chunk-HHAQUBXP.js.map
  docs/.vitepress/cache/deps/chunk-R647EDCJ.js
  docs/.vitepress/cache/deps/chunk-R647EDCJ.js.map
  docs/.vitepress/cache/deps/package.json
  docs/.vitepress/cache/deps/vue.js
  docs/.vitepress/cache/deps/vue.js.map
  package.json
Labels: documentation

#44 add new article
  docs/.vitepress/config.ts
  docs/posts/2022-03-10-calsium-channel-in-the-heart.md
Labels: documentation, New article
